In [2]:
import os
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, LeakyReLU, Dropout, MaxPool2D, BatchNormalization
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.regularizers import l2

In [3]:
df = pd.read_csv('train.csv')
df.head()

          ID   Class
0    377.jpg  MIDDLE
1  17814.jpg   YOUNG
2  21283.jpg  MIDDLE
3  16496.jpg   YOUNG
4   4487.jpg  MIDDLE

In [4]:
df.isnull().sum()

ID       0
Class    0
dtype: int64

In [5]:
df.describe()

             ID   Class
count     19906   19906
unique    19906       3
top     377.jpg  MIDDLE
freq          1   10804

In [6]:
import zipfile

In [7]:
"""
zip_ref = zipfile.ZipFile('./faces.zip', 'r')
zip_ref.extractall('./')
zip_ref.close()
"""

"\nzip_ref = zipfile.ZipFile('./faces.zip', 'r')\nzip_ref.extractall('./')\nzip_ref.close()\n"

In [8]:
a = os.listdir('./faces/train')
a[2]

'100.jpg'

In [9]:
from PIL import Image
import matplotlib.pyplot as plt

In [10]:
data = []
labels = []
for i in range(len(a)):
    img = Image.open('./faces/Train/' + a[i])
    img = img.resize((80,80))
    img = np.array(img)
    data.append(img)
    class_value = df[df['ID'] == a[i]]['Class'].values[0]
    if class_value == 'YOUNG':
        labels.append(0)
    elif class_value == "MIDDLE":
        labels.append(1)
    else:
        labels.append(2)
print('Done')

Done

In [11]:
temp = df[df['ID'] == '377.jpg']['Class'].values[0]
temp

'MIDDLE'

In [12]:
data_array = np.asarray(data)
data_array = data_array / 255.0
labels_array = np.asarray(labels)
labels_hot = to_categorical(labels_array, num_classes=3)
print(f"data: {data_array.shape}, \nhot: {labels_hot.shape}")

data: (19906, 80, 80, 3),
hot: (19906, 3)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain, xtest, ytrain, ytest = train_test_split(data_array, labels_hot, test_size=0.1, random_state=42)

In [15]:
print(f'Train:\n{xtrain.shape}\n{ytrain.shape}\nTest:\n{xtest.shape}\n{ytest.shape}')

Train:
(17915, 80, 80, 3)
(17915, 3)
Test:
(1991, 80, 80, 3)
(1991, 3)

In [16]:
model = Sequential()

model.add(Conv2D(16, (3,3), input_shape=(80,80,3)))
#model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(16, (3,3)))
#model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling2D(2,2))
#model.add(Conv2D(128, (3,3)))
#model.add(Conv2D(128, (3,3)))
#model.add(Conv2D(16, (3,3), activation='relu'))
#model.add(MaxPooling2D(2,2))


model.add(Flatten())
model.add(Dense(256, activation = 'relu', kernel_regularizer=l2(0.01)))
model.add(Dense(256, activation = 'relu', kernel_regularizer=l2(0.01)))
model.add(Dense(128, activation = 'relu', kernel_regularizer=l2(0.01)))
model.add(Dense(3, activation='softmax'))

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 78, 78, 16)        448

 max_pooling2d (MaxPooling2D  (None, 39, 39, 16)       0
 )

 conv2d_1 (Conv2D)           (None, 37, 37, 16)        2320

 max_pooling2d_1 (MaxPooling  (None, 18, 18, 16)       0
 2D)

 flatten (Flatten)           (None, 5184)              0

 dense (Dense)               (None, 256)               1327360

 dense_1 (Dense)             (None, 256)               65792

 dense_2 (Dense)             (None, 128)               32896

 dense_3 (Dense)             (None, 3)                 387

=================================================================
Total params: 1,429,203
Trainable params: 1,429,203
Non-trainable params: 0
_________________________________________________________________

In [18]:
model.compile(optimizer = Adam() , loss = 'categorical_crossentropy', metrics = ['acc'])

In [21]:
class MyCallback(tf.keras.callbacks.Callback):
    def epoch_on_end(self, epochs, logs={}):
        if logs.get('accuracy') > 0.9:
            print("condition satisfied")
            self.model.stop_training = True

callbacks = MyCallback()

In [22]:
model.fit(xtrain, ytrain, batch_size=10, epochs=50, validation_split=0.1, callbacks=[callbacks])

Epoch 1/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.8343 - acc: 0.6555 - val_loss: 0.8241 - val_acc: 0.6602
Epoch 2/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.8216 - acc: 0.6579 - val_loss: 0.8350 - val_acc: 0.6490
Epoch 3/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.8155 - acc: 0.6614 - val_loss: 0.8234 - val_acc: 0.6496
Epoch 4/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.8105 - acc: 0.6623 - val_loss: 0.8384 - val_acc: 0.6412
Epoch 5/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.8110 - acc: 0.6641 - val_loss: 0.8134 - val_acc: 0.6618
Epoch 6/50
1613/1613 [==============================] - 31s 19ms/step - loss: 0.8046 - acc: 0.6682 - val_loss: 0.8091 - val_acc: 0.6669
Epoch 7/50
1613/1613 [==============================] - 31s 19ms/step - loss: 0.8026 - acc: 0.6697 - val_loss: 0.8164 - val_acc: 0.6624
Epoch 8/50
1613/1613 [==============================] - 31s 19ms/step - loss: 0.7993 - acc: 0.6677 - val_loss: 0.8160 - val_acc: 0.6680
Epoch 9/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7972 - acc: 0.6695 - val_loss: 0.8215 - val_acc: 0.6635
Epoch 10/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7952 - acc: 0.6723 - val_loss: 0.8256 - val_acc: 0.6479
Epoch 11/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7930 - acc: 0.6714 - val_loss: 0.8078 - val_acc: 0.6607
Epoch 12/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7938 - acc: 0.6696 - val_loss: 0.8145 - val_acc: 0.6551
Epoch 13/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7895 - acc: 0.6721 - val_loss: 0.8247 - val_acc: 0.6468
Epoch 14/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7876 - acc: 0.6738 - val_loss: 0.8071 - val_acc: 0.6713
Epoch 15/50
1613/1613 [==============================] - 31s 19ms/step - loss: 0.7878 - acc: 0.6756 - val_loss: 0.8117 - val_acc: 0.6663
Epoch 16/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7824 - acc: 0.6790 - val_loss: 0.7957 - val_acc: 0.6719
Epoch 17/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7862 - acc: 0.6739 - val_loss: 0.7981 - val_acc: 0.6730
Epoch 18/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7858 - acc: 0.6770 - val_loss: 0.7940 - val_acc: 0.6747
Epoch 19/50
1613/1613 [==============================] - 33s 20ms/step - loss: 0.7835 - acc: 0.6769 - val_loss: 0.7984 - val_acc: 0.6780
Epoch 20/50
1613/1613 [==============================] - 33s 20ms/step - loss: 0.7826 - acc: 0.6800 - val_loss: 0.7880 - val_acc: 0.6669
Epoch 21/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7816 - acc: 0.6773 - val_loss: 0.8016 - val_acc: 0.6730
Epoch 22/50
1613/1613 [==============================] - 33s 20ms/step - loss: 0.7823 - acc: 0.6785 - val_loss: 0.8007 - val_acc: 0.6758
Epoch 23/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7779 - acc: 0.6808 - val_loss: 0.7966 - val_acc: 0.6797
Epoch 24/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7792 - acc: 0.6799 - val_loss: 0.8115 - val_acc: 0.6680
Epoch 25/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7791 - acc: 0.6809 - val_loss: 0.8038 - val_acc: 0.6758
Epoch 26/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7739 - acc: 0.6805 - val_loss: 0.8050 - val_acc: 0.6663
Epoch 27/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7760 - acc: 0.6863 - val_loss: 0.7993 - val_acc: 0.6747
Epoch 28/50
1613/1613 [==============================] - 33s 20ms/step - loss: 0.7747 - acc: 0.6818 - val_loss: 0.8156 - val_acc: 0.6702
Epoch 29/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7715 - acc: 0.6842 - val_loss: 0.7900 - val_acc: 0.6802
Epoch 30/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7727 - acc: 0.6828 - val_loss: 0.8147 - val_acc: 0.6490
Epoch 31/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7710 - acc: 0.6844 - val_loss: 0.7946 - val_acc: 0.6847
Epoch 32/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7697 - acc: 0.6875 - val_loss: 0.7972 - val_acc: 0.6719
Epoch 33/50
1613/1613 [==============================] - 32s 20ms/step - loss: 0.7715 - acc: 0.6825 - val_loss: 0.7844 - val_acc: 0.6802
Epoch 34/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7706 - acc: 0.6885 - val_loss: 0.8081 - val_acc: 0.6646
Epoch 35/50
1613/1613 [==============================] - 33s 21ms/step - loss: 0.7691 - acc: 0.6867 - val_loss: 0.7973 - val_acc: 0.6724
Epoch 36/50
1613/1613 [==============================] - 33s 21ms/step - loss: 0.7715 - acc: 0.6873 - val_loss: 0.7996 - val_acc: 0.6769
Epoch 37/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7705 - acc: 0.6842 - val_loss: 0.7914 - val_acc: 0.6691
Epoch 38/50
1613/1613 [==============================] - 35s 21ms/step - loss: 0.7696 - acc: 0.6857 - val_loss: 0.8142 - val_acc: 0.6724
Epoch 39/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7687 - acc: 0.6865 - val_loss: 0.8062 - val_acc: 0.6624
Epoch 40/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7671 - acc: 0.6876 - val_loss: 0.8216 - val_acc: 0.6574
Epoch 41/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7689 - acc: 0.6827 - val_loss: 0.8107 - val_acc: 0.6562
Epoch 42/50
1613/1613 [==============================] - 35s 21ms/step - loss: 0.7672 - acc: 0.6907 - val_loss: 0.8069 - val_acc: 0.6719
Epoch 43/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7683 - acc: 0.6887 - val_loss: 0.8002 - val_acc: 0.6775
Epoch 44/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7666 - acc: 0.6883 - val_loss: 0.7979 - val_acc: 0.6752
Epoch 45/50
1613/1613 [==============================] - 34s 21ms/step - loss: 0.7672 - acc: 0.6853 - val_loss: 0.8125 - val_acc: 0.6618
Epoch 46/50
1613/1613 [==============================] - 35s 22ms/step - loss: 0.7687 - acc: 0.6875 - val_loss: 0.8050 - val_acc: 0.6702
Epoch 47/50
1613/1613 [==============================] - 35s 22ms/step - loss: 0.7624 - acc: 0.6909 - val_loss: 0.8505 - val_acc: 0.6412
Epoch 48/50
1613/1613 [==============================] - 35s 22ms/step - loss: 0.7674 - acc: 0.6885 - val_loss: 0.7944 - val_acc: 0.6702
Epoch 49/50
1613/1613 [==============================] - 35s 22ms/step - loss: 0.7645 - acc: 0.6867 - val_loss: 0.8476 - val_acc: 0.6496
Epoch 50/50
1613/1613 [==============================] - 35s 22ms/step - loss: 0.7624 - acc: 0.6899 - val_loss: 0.7957 - val_acc: 0.6864

In [23]:
model.evaluate(xtest, ytest)

63/63 [==============================] - 1s 10ms/step - loss: 0.7795 - acc: 0.6876

[0.7794857621192932, 0.6875941753387451]